export enum Languages {
  JAVASCRIPT = 'javascript',
  TYPESCRIPT = 'typescript',
  PYTHON = 'python',
  JAVA = 'java',
  C = 'c',
  CPP = 'cpp',
  CSHARP = 'csharp',
  GO = 'go',
  RUST = 'rust',
  RUBY = 'ruby',
  PHP = 'php',
  BASH = 'bash',
}

export const languageExtensions: { [key: string]: string } = {
  javascript: '.js',
  typescript: '.ts',
  python: '.py',
  java: '.java',
  c: '.c',
  cpp: '.cpp',
  csharp: '.cs',
  go: '.go',
  rust: '.rs',
  ruby: '.rb',
  php: '.php',
  bash: '.sh',
  html: '.html',
  css: '.css',
  json: '.json',
  markdown: '.md',
}

export const languageOptions: { label: string; value: Languages }[] = [
  { label: 'JavaScript', value: Languages.JAVASCRIPT },
  { label: 'TypeScript', value: Languages.TYPESCRIPT },
  { label: 'Python', value: Languages.PYTHON },
  { label: 'Java', value: Languages.JAVA },
  { label: 'C', value: Languages.C },
  { label: 'C++', value: Languages.CPP },
  { label: 'C#', value: Languages.CSHARP },
  { label: 'Go', value: Languages.GO },
  { label: 'Rust', value: Languages.RUST },
  { label: 'Ruby', value: Languages.RUBY },
  { label: 'PHP', value: Languages.PHP },
  { label: 'Bash', value: Languages.BASH },
]
